# Generated by Django 5.2.5 on 2025-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='contact_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='last_year_attended',
            field=models.CharField(max_length=100),
        ),
    ]
