# Generated by Django 5.2.5 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_alter_department_email_alter_student_lrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
