# Generated by Django 5.2.8 on 2025-11-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_department_phone_no_alter_schedule_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingDatabase',
        ),
    ]
